<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Splits the per-financial-year invoice number counter into two independent
 * sequences ('domestic' / 'export') so InvoiceNumberGenerator can track
 * India-billed and out-of-India-billed clients separately, matching the
 * team's real Hitech numbering (e.g. 26/27-040 vs 26/27-IN022). Existing
 * rows default to 'domestic' -- every invoice number generated by this app
 * to date has been for a domestic (India) client, so this is a truthful
 * backfill, not a guess.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('invoice_number_sequences', function (Blueprint $table) {
            $table->string('sequence_type')->default('domestic')->after('financial_year');
        });

        Schema::table('invoice_number_sequences', function (Blueprint $table) {
            $table->dropUnique(['financial_year']);
            $table->unique(['financial_year', 'sequence_type']);
        });
    }

    public function down(): void
    {
        Schema::table('invoice_number_sequences', function (Blueprint $table) {
            $table->dropUnique(['financial_year', 'sequence_type']);
            $table->unique('financial_year');
            $table->dropColumn('sequence_type');
        });
    }
};
