<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * "Best Employee of the Quarter" — AI-suggested, Admin/Manager-approved
 * recognition per financial-year quarter. One row per department winner
 * (department = a UserRole value) plus one company-wide row
 * (department = 'company'), generated by App\Services\QuarterlyAwardGenerator
 * from App\Services\ReportMetrics::rankedEmployeePerformance()'s existing
 * percentile scoring — no new metrics collected. Certificate + citation
 * only, no tracked reward amount (see the Sales Incentive module for
 * money-based recognition).
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('quarterly_awards', function (Blueprint $table) {
            $table->id();
            $table->string('financial_year'); // e.g. "2026-27"
            $table->unsignedTinyInteger('quarter'); // 1 (Apr-Jun) .. 4 (Jan-Mar)
            $table->string('department'); // a UserRole value, or 'company' for the company-wide award
            $table->foreignId('user_id')->constrained('users');
            $table->unsignedTinyInteger('score')->nullable(); // 0-100, from rankedEmployeePerformance() at generation time
            $table->text('citation')->nullable(); // AI-drafted, editable at approval
            $table->string('status')->default('pending');
            $table->foreignId('reviewed_by')->nullable()->constrained('users');
            $table->timestamp('reviewed_at')->nullable();
            $table->foreignId('announcement_id')->nullable()->constrained('announcements')->nullOnDelete();
            $table->timestamp('notified_at')->nullable();
            $table->timestamps();

            $table->unique(['financial_year', 'quarter', 'department']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('quarterly_awards');
    }
};
