<?php

use App\Enums\InvoiceStatus;
use App\Enums\UserRole;
use App\Livewire\RecurringInvoiceBuilder;
use App\Mail\InvoiceIssued;
use App\Models\Customer;
use App\Models\Invoice;
use App\Models\RecurringInvoice;
use App\Models\User;
use Database\Seeders\MenuItemsSeeder;
use Illuminate\Support\Facades\Mail;
use Livewire\Livewire;

function recurringWithLine(array $attributes = []): RecurringInvoice
{
    $template = RecurringInvoice::factory()->create(array_merge([
        'customer_id' => Customer::factory()->create(['state_code' => '27', 'email' => 'client@x.test'])->id,
    ], $attributes));

    $template->items()->create([
        'description' => 'Monthly SEO retainer', 'sac_code' => '998361',
        'quantity' => 1, 'rate' => 100000, 'gst_rate' => 18,
    ]);

    return $template->refresh();
}

it('generates an invoice for a due template, emails it, and advances the schedule', function () {
    Mail::fake();
    $template = recurringWithLine(['next_run_on' => now()->subDay()->toDateString()]);

    $this->artisan('app:generate-recurring-invoices')->assertSuccessful();

    $invoice = Invoice::first();
    expect($invoice)->not->toBeNull()
        ->and($invoice->total)->toBe(118000)
        ->and($invoice->customer_id)->toBe($template->customer_id);

    Mail::assertSent(InvoiceIssued::class, fn (InvoiceIssued $m) => $m->hasTo('client@x.test'));

    expect($template->fresh()->next_run_on->greaterThan(now()))->toBeTrue();
});

it('carries the template\'s own GST-exempt flag onto a generated recurring invoice', function () {
    Mail::fake();
    $exemptCustomer = Customer::factory()->create(['state_code' => '27', 'email' => 'exempt@x.test', 'gst_exempt' => true]);
    recurringWithLine(['customer_id' => $exemptCustomer->id, 'is_gst_exempt' => true, 'next_run_on' => now()->subDay()->toDateString()]);

    $this->artisan('app:generate-recurring-invoices')->assertSuccessful();

    $invoice = Invoice::first();
    expect($invoice->is_gst_exempt)->toBeTrue()
        ->and($invoice->cgst_total)->toBe(0)
        ->and($invoice->total)->toBe(100000);
});

it('skips templates that are not yet due', function () {
    Mail::fake();
    recurringWithLine(['next_run_on' => now()->addWeek()->toDateString()]);

    $this->artisan('app:generate-recurring-invoices')->assertSuccessful();

    expect(Invoice::count())->toBe(0);
});

it('generates via the "Generate & Send Now" button, self-healing a drifted invoice-number counter', function () {
    $this->seed(MenuItemsSeeder::class);
    Mail::fake();

    // Reproduces the production bug: a manually-logged invoice landed ahead of
    // the invoice_number_sequences counter, so the counter is stuck behind the
    // real max and a naive generate() call would collide on every attempt.
    $manuallyLogged = Invoice::factory()->create();
    $manuallyLogged->update(['invoice_number' => 'NEDS/'.$manuallyLogged->financial_year.'/0050']);

    $template = recurringWithLine(['next_run_on' => now()->addWeek()->toDateString()]);
    $accounts = User::factory()->role(UserRole::Accounts)->create();

    $response = $this->actingAs($accounts)->post(route('recurring-invoices.generate-now', $template));

    $response->assertRedirect(route('recurring-invoices.show', $template));
    $invoice = Invoice::where('recurring_invoice_id', $template->id)->first();
    expect($invoice)->not->toBeNull()
        ->and($invoice->invoice_number)->not->toBe($manuallyLogged->invoice_number);

    Mail::assertSent(InvoiceIssued::class);
});

it('carries the GST-exempt default onto invoices generated by the daily command even after the customer flag later changes', function () {
    Mail::fake();
    $customer = Customer::factory()->create(['state_code' => '27', 'email' => 'client@x.test', 'gst_exempt' => true]);
    $template = recurringWithLine(['customer_id' => $customer->id, 'is_gst_exempt' => true, 'next_run_on' => now()->subDay()->toDateString()]);

    // The customer later stops being GST-exempt — the template's own stored
    // flag must still win, not a live re-read of the customer.
    $customer->update(['gst_exempt' => false]);

    $this->artisan('app:generate-recurring-invoices')->assertSuccessful();

    $invoice = Invoice::first();
    expect($invoice->is_gst_exempt)->toBeTrue()
        ->and($invoice->cgst_total)->toBe(0)
        ->and($invoice->total)->toBe(100000);
});

it('carries the GST-exempt flag through "Generate & Send Now" too', function () {
    $this->seed(MenuItemsSeeder::class);
    Mail::fake();
    $accounts = User::factory()->role(UserRole::Accounts)->create();
    $template = recurringWithLine(['is_gst_exempt' => true, 'next_run_on' => now()->addWeek()->toDateString()]);

    $this->actingAs($accounts)->post(route('recurring-invoices.generate-now', $template))->assertRedirect();

    $invoice = Invoice::where('recurring_invoice_id', $template->id)->first();
    expect($invoice->is_gst_exempt)->toBeTrue()
        ->and($invoice->cgst_total)->toBe(0);
});

it('defaults the RecurringInvoiceBuilder GST-exempt toggle from the selected client, and can still be overridden', function () {
    $admin = User::factory()->role(UserRole::Admin)->create();
    $exemptClient = Customer::factory()->create(['state_code' => '27', 'gst_exempt' => true]);
    $normalClient = Customer::factory()->create(['state_code' => '27', 'gst_exempt' => false]);

    Livewire::actingAs($admin)
        ->test(RecurringInvoiceBuilder::class)
        ->set('customer_id', $exemptClient->id)
        ->assertSet('is_gst_exempt', true)
        ->set('customer_id', $normalClient->id)
        ->assertSet('is_gst_exempt', false)
        ->set('is_gst_exempt', true) // manual override survives the save
        ->set('items', [[
            'description' => 'SEO retainer', 'sac_code' => '998361',
            'quantity' => '1', 'rate' => '1000', 'gst_rate' => '18',
        ]])
        ->call('save')
        ->assertHasNoErrors();

    expect(RecurringInvoice::first()->is_gst_exempt)->toBeTrue();
});

it('shows a note and disables the per-item GST% field when Non-GST is checked', function () {
    $admin = User::factory()->role(UserRole::Admin)->create();
    $client = Customer::factory()->create(['state_code' => '27']);

    Livewire::actingAs($admin)
        ->test(RecurringInvoiceBuilder::class)
        ->set('customer_id', $client->id)
        ->set('is_gst_exempt', true)
        ->assertSee('the GST% below is ignored')
        ->assertSeeHtml('disabled');
});

it('deactivates a template once it passes its end date', function () {
    Mail::fake();
    $template = recurringWithLine([
        'next_run_on' => now()->subDay()->toDateString(),
        'end_date' => now()->toDateString(),
    ]);

    $this->artisan('app:generate-recurring-invoices')->assertSuccessful();

    expect($template->fresh()->is_active)->toBeFalse();
});

it('hasEnded is true only when inactive with a past end date, not a manual pause', function () {
    $ended = recurringWithLine(['is_active' => false, 'end_date' => now()->subDay()->toDateString()]);
    $pausedNoEndDate = recurringWithLine(['is_active' => false, 'end_date' => null]);
    $pausedFutureEndDate = recurringWithLine(['is_active' => false, 'end_date' => now()->addMonth()->toDateString()]);
    $activePastEndDate = recurringWithLine(['is_active' => true, 'end_date' => now()->subDay()->toDateString()]);

    expect($ended->hasEnded())->toBeTrue()
        ->and($pausedNoEndDate->hasEnded())->toBeFalse()
        ->and($pausedFutureEndDate->hasEnded())->toBeFalse()
        ->and($activePastEndDate->hasEnded())->toBeFalse();
});

it('dashboardStatus: upcoming when start_date is in the future', function () {
    $r = recurringWithLine(['start_date' => now()->addWeek()->toDateString(), 'end_date' => now()->addMonth()->toDateString()]);

    expect($r->dashboardStatus())->toBe('upcoming');
});

it('dashboardStatus: active when within its period and is_active', function () {
    $r = recurringWithLine(['start_date' => now()->subDays(5)->toDateString(), 'end_date' => now()->addDays(5)->toDateString(), 'is_active' => true]);

    expect($r->dashboardStatus())->toBe('active');
});

it('dashboardStatus: on_hold when within its period but paused', function () {
    $r = recurringWithLine(['start_date' => now()->subDays(5)->toDateString(), 'end_date' => now()->addDays(5)->toDateString(), 'is_active' => false]);

    expect($r->dashboardStatus())->toBe('on_hold');
});

it('dashboardStatus: payment_received when the period is over and its invoice is paid', function () {
    $r = recurringWithLine(['start_date' => now()->subMonth()->toDateString(), 'end_date' => now()->subDay()->toDateString(), 'is_active' => false]);
    Invoice::factory()->status(InvoiceStatus::Paid)->create(['recurring_invoice_id' => $r->id, 'customer_id' => $r->customer_id]);
    $r->load('invoices');

    expect($r->dashboardStatus())->toBe('payment_received');
});

it('dashboardStatus: payment_pending when the period is over and its invoice is unpaid', function () {
    $r = recurringWithLine(['start_date' => now()->subMonth()->toDateString(), 'end_date' => now()->subDay()->toDateString(), 'is_active' => false]);
    Invoice::factory()->status(InvoiceStatus::Sent)->create(['recurring_invoice_id' => $r->id, 'customer_id' => $r->customer_id]);
    $r->load('invoices');

    expect($r->dashboardStatus())->toBe('payment_pending');
});

it('dashboardStatus: ended when the period is over and no invoice was ever generated', function () {
    $r = recurringWithLine(['start_date' => now()->subMonth()->toDateString(), 'end_date' => now()->subDay()->toDateString(), 'is_active' => false]);

    expect($r->dashboardStatus())->toBe('ended');
});

it('dashboardStatus: falls back to ended (not payment detail) when the viewer lacks invoice access', function () {
    $r = recurringWithLine(['start_date' => now()->subMonth()->toDateString(), 'end_date' => now()->subDay()->toDateString(), 'is_active' => false]);
    Invoice::factory()->status(InvoiceStatus::Paid)->create(['recurring_invoice_id' => $r->id, 'customer_id' => $r->customer_id]);
    $r->load('invoices');

    expect($r->dashboardStatus(revealPaymentStatus: false))->toBe('ended');
});

it('isOrphaned: true when paused with an invoice that was generated then deleted', function () {
    $r = recurringWithLine(['is_active' => false]);
    Invoice::factory()->create(['recurring_invoice_id' => $r->id, 'customer_id' => $r->customer_id])->delete();

    expect($r->isOrphaned())->toBeTrue();
});

it('isOrphaned: false when paused but never billed at all (a genuine manual pause)', function () {
    $r = recurringWithLine(['is_active' => false]);

    expect($r->isOrphaned())->toBeFalse();
});

it('isOrphaned: false when paused with a surviving (non-deleted) invoice', function () {
    $r = recurringWithLine(['is_active' => false]);
    Invoice::factory()->create(['recurring_invoice_id' => $r->id, 'customer_id' => $r->customer_id]);

    expect($r->isOrphaned())->toBeFalse();
});

it('isOrphaned: false when active, even with a deleted invoice', function () {
    $r = recurringWithLine(['is_active' => true]);
    Invoice::factory()->create(['recurring_invoice_id' => $r->id, 'customer_id' => $r->customer_id])->delete();

    expect($r->isOrphaned())->toBeFalse();
});

it('scopeDue excludes an active template whose next_run_on has drifted past its own end_date', function () {
    // Reproduces the reactivated-after-auto-pause trap: is_active=true but
    // next_run_on is already beyond end_date — should never be "due".
    $stale = recurringWithLine([
        'is_active' => true,
        'end_date' => now()->subDay()->toDateString(),
        'next_run_on' => now()->toDateString(),
    ]);
    $normal = recurringWithLine([
        'is_active' => true,
        'end_date' => now()->addMonth()->toDateString(),
        'next_run_on' => now()->toDateString(),
    ]);

    $due = RecurringInvoice::due(now())->pluck('id');

    expect($due)->not->toContain($stale->id)
        ->and($due)->toContain($normal->id);
});

it('isStaleActive: true only when active with next_run_on past end_date', function () {
    $stale = recurringWithLine(['is_active' => true, 'end_date' => now()->subDay()->toDateString(), 'next_run_on' => now()->toDateString()]);
    $normalActive = recurringWithLine(['is_active' => true, 'end_date' => now()->addMonth()->toDateString(), 'next_run_on' => now()->toDateString()]);
    $pausedPastEnd = recurringWithLine(['is_active' => false, 'end_date' => now()->subDay()->toDateString(), 'next_run_on' => now()->toDateString()]);
    $noEndDate = recurringWithLine(['is_active' => true, 'end_date' => null, 'next_run_on' => now()->addYear()->toDateString()]);

    expect($stale->isStaleActive())->toBeTrue()
        ->and($normalActive->isStaleActive())->toBeFalse()
        ->and($pausedPastEnd->isStaleActive())->toBeFalse()
        ->and($noEndDate->isStaleActive())->toBeFalse();
});

it('self-heals a stale-active template back to paused instead of generating a duplicate invoice', function () {
    Mail::fake();
    $stale = recurringWithLine([
        'is_active' => true,
        'end_date' => now()->subDay()->toDateString(),
        'next_run_on' => now()->toDateString(),
    ]);

    $this->artisan('app:generate-recurring-invoices')->assertSuccessful();

    expect($stale->fresh()->is_active)->toBeFalse()
        ->and(Invoice::where('recurring_invoice_id', $stale->id)->exists())->toBeFalse();
});

it('allows reactivating a template whose next_run_on is past its end_date — e.g. to regenerate a corrected invoice or bill a pending historical month', function () {
    $this->seed(MenuItemsSeeder::class);
    $accounts = User::factory()->role(UserRole::Accounts)->create();
    $stale = recurringWithLine([
        'is_active' => false,
        'end_date' => now()->subDay()->toDateString(),
        'next_run_on' => now()->toDateString(),
    ]);

    $response = $this->actingAs($accounts)->put(route('recurring-invoices.toggle', $stale));

    $response->assertRedirect();
    expect($stale->fresh()->is_active)->toBeTrue();
});

it('still allows toggling a normal paused template back to active', function () {
    $this->seed(MenuItemsSeeder::class);
    $accounts = User::factory()->role(UserRole::Accounts)->create();
    $normal = recurringWithLine([
        'is_active' => false,
        'end_date' => now()->addMonth()->toDateString(),
        'next_run_on' => now()->toDateString(),
    ]);

    $response = $this->actingAs($accounts)->put(route('recurring-invoices.toggle', $normal));

    $response->assertRedirect();
    expect($normal->fresh()->is_active)->toBeTrue();
});

it('hides Ended templates from the Recurring Invoices list by default', function () {
    $this->seed(MenuItemsSeeder::class);
    $accounts = User::factory()->role(UserRole::Accounts)->create();
    $ended = recurringWithLine(['is_active' => false, 'end_date' => now()->subDay()->toDateString()]);
    $paused = recurringWithLine(['is_active' => false, 'end_date' => null]);
    $active = recurringWithLine(['is_active' => true]);

    $response = $this->actingAs($accounts)->get(route('recurring-invoices.index'));

    $response->assertOk()
        ->assertSee($paused->customer->company_name)
        ->assertSee($active->customer->company_name)
        ->assertDontSee($ended->customer->company_name);
});

it('shows Ended templates on the Recurring Invoices list when show_ended=1', function () {
    $this->seed(MenuItemsSeeder::class);
    $accounts = User::factory()->role(UserRole::Accounts)->create();
    $ended = recurringWithLine(['is_active' => false, 'end_date' => now()->subDay()->toDateString()]);

    $this->actingAs($accounts)
        ->get(route('recurring-invoices.index', ['show_ended' => 1]))
        ->assertOk()
        ->assertSee($ended->customer->company_name)
        ->assertSee('Ended');
});
